/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER E5-471
 */
public class Aritmatika extends javax.swing.JFrame {
 String jns = "";
 int jml;
    /**
  
     */
    public Aritmatika() {
        initComponents();
        jns = null;
        panel.hide();
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        jml=2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jmlBil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        bil4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        thasil = new javax.swing.JTextArea();
        bil1 = new javax.swing.JTextField();
        hasil = new javax.swing.JButton();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 120, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "Penjumlahan", "Pengurangan", "Pembagian", "Perkalian", " " }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(240, 60, 150, 40);

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));
        jPanel3.setLayout(null);

        panel.setBackground(new java.awt.Color(153, 255, 153));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        panel.setLayout(null);

        jmlBil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", " " }));
        jmlBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlBilActionPerformed(evt);
            }
        });
        panel.add(jmlBil);
        jmlBil.setBounds(180, 80, 130, 30);

        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(70, 80, 90, 30);

        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(80, 250, 90, 20);

        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(80, 210, 90, 20);

        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(80, 170, 90, 20);

        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(80, 130, 90, 20);
        panel.add(bil4);
        bil4.setBounds(180, 240, 130, 30);

        thasil.setColumns(20);
        thasil.setRows(5);
        jScrollPane1.setViewportView(thasil);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(46, 340, 280, 96);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1);
        bil1.setBounds(180, 120, 130, 30);

        hasil.setText("Hitung");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(140, 290, 90, 40);
        panel.add(bil2);
        bil2.setBounds(180, 160, 130, 30);

        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        panel.add(bil3);
        bil3.setBounds(180, 200, 130, 30);
        panel.add(ket);
        ket.setBounds(130, 20, 120, 40);

        jPanel3.add(panel);
        panel.setBounds(50, 110, 360, 450);

        jLabel1.setFont(new java.awt.Font("SimHei", 0, 24)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(120, 10, 240, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, 0, 460, 580);

        setBounds(0, 0, 464, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
             // TODO add your handling code here:
             SetJenis();
    }
    
    public void SetJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
         else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
         else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            jmlBil.setEnabled(true);
        }
    
    }//GEN-LAST:event_jenisActionPerformed

    private void jmlBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlBilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jmlBilActionPerformed

    public void getJumlah(){
        if(jmlBil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml=2;
        }else if(jmlBil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml=3;
        }else if(jmlBil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml=4;
        }
    }
    
    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil3ActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        Double hasil = 0.0;
        Double a1, a2, a3, a4=0.0;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
     switch (jns) {
         case "Penjumlahan":
             if(jml ==2){
                 hasil = a1+a2;
                 thasil.append(""+a1+"+"+a2+"="+ hasil);
             }if(jml ==3){
                 a3= Double.parseDouble(bil3.getText().toString());
                 hasil = a1+a2+a3;
                 thasil.append(""+a1+"+"+a2+"+"+a3 +"="+ hasil);
                 
             }if(jml ==4){
                 a3= Double.parseDouble(bil3.getText().toString());
                 a4=Double.parseDouble(bil4.getText().toString());
                 hasil = a1+a2+a3+a4;
                 thasil.setText(""+a1+"+"+a2+"+"+a3+"+"+a4+"="+ hasil);
             }    break;
         case "Pengurangan":
             if(jml ==2){
                 hasil = a1-a2;
                 thasil.setText(""+a1+"-"+a2+"="+ hasil);
             }if(jml ==3){
                 a3= Double.parseDouble(bil3.getText().toString());
                 hasil = a1-a2-a3;
                 thasil.setText(""+a1+"-"+a2+"-"+a3 +"="+ hasil);
                 
             }if(jml ==4){
                 a3= Double.parseDouble(bil3.getText().toString());
                 a4=Double.parseDouble(bil4.getText().toString());
                 hasil = a1-a2-a3-a4;
                 thasil.setText(""+a1+"-"+a2+"-"+a3+"-"+a4+"="+ hasil);
             }    break;
         case "Perkalian":
             if(jml ==2){
                 hasil = a1*a2;
                 thasil.setText(""+a1+"x"+a2+"="+ hasil);
             }if(jml ==3){
                 a3= Double.parseDouble(bil3.getText().toString());
                 hasil = a1*a2*a3;
                 thasil.setText(""+a1+"x"+a2+"x"+a3 +"="+ hasil);
                 
             }if(jml ==4){
                 a3= Double.parseDouble(bil3.getText().toString());
                 a4=Double.parseDouble(bil4.getText().toString());
                 hasil = a1*a2*a3*a4;
                 thasil.setText(""+a1+"x"+a2+"x"+a3+"x"+a4+"="+ hasil);
             }    break;
         case "Pembagian":
             if(jml ==2){
                 hasil = a1/a2;
                 thasil.setText(""+a1+":"+a2+"="+ hasil);
             }if(jml ==3){
                 a3= Double.parseDouble(bil3.getText().toString());
                 hasil = a1/a2/a3;
                 thasil.setText(""+a1+":"+a2+":"+a3 +"="+ hasil);
                 
             }if(jml ==4){
                 a3= Double.parseDouble(bil3.getText().toString());
                 a4=Double.parseDouble(bil4.getText().toString());
                 hasil = a1/a2/a3/a4;
                 thasil.setText(""+a1+":"+a2+":"+a3+":"+a4+"="+ hasil);
             }    break;
         default:
             break;
     }                               
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jmlBil;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea thasil;
    // End of variables declaration//GEN-END:variables
}
